server:
    port: 8762
spring:
    application:
        name: service-helloworld
eureka:
    instance:
        hostname: 192.168.0.106
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/